# -*- coding: utf-8 -*-
"""first_enhancer_preprocessing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1loDN9oCacE1o4W6lm4NxAu4jbf7LmO4S
"""

from google.colab import drive
drive.mount('/content/drive')

PATH1 = "/content/drive/MyDrive/BIO_info/hglft_genome_15392_fdce0.bed" # path per gene + indici

class gene:
    def __init__(self, nome, ind_start, ind_end):
        self.nome = nome
        self.ind_start = ind_start
        self.ind_end = ind_end
    def __str__(self):
        return "Gene: "+ str(self.nome) +" start index: "+ str(self.ind_start) +" end index: "+ str(self.ind_end)+"\n"

"""Recuperiamo dal file .bed (formato chrX:start-end) i nomi dei geni e gli indici di inzio e fine degli enhancer da recuperare

"""

import re

with open(PATH1,"r") as file_bed:
    my_list = []
    for line in file_bed:
        match = re.match(r'^(\w+):(\d+)-(\d+)$', line)
        if match:
            sequence_id = match.group(1)
            sequence_start = int(match.group(2))
            sequence_end = int(match.group(3))
        tmp = gene(sequence_id, sequence_start, sequence_end)
        my_list.append(tmp)

for item in my_list:
    print(item)

"""Recuperiamo gli enhancer"""

pip install biopython

from Bio import SeqIO

# Carica il file FASTA
fasta_file = "/content/drive/MyDrive/BIO_info/GRCh38.p14.genome.fa"
#genome = SeqIO.read(fasta_file, "fasta")

class fasta_elem:
    def __init__(self, nome, sequence):
        self.nome = nome
        self.sequence = sequence
    def __str__(self):
        return "Gene: "+ str(self.nome) +" sequence: "+ str(self.sequence)+"\n"

from Bio import SeqIO

fasta_list = []

# Apri il file .fa e leggi le sequenze
with open(fasta_file, "r") as handle:
    for record in SeqIO.parse(handle, "fasta"):
       id = record.id
       sequence = record.seq
       tmp = fasta_elem(id, sequence)
       fasta_list.append(tmp)

"""a noi servono esclusivamento i geni fino al 22"""

fasta_list = fasta_list[0:22]

len(fasta_list)

for elem in fasta_list:
  print(elem.nome + "\n")

"""recupero delle sequence degli enhancer e le salvo nel file enhancer.txt

"""

enhancer_file = "/content/drive/MyDrive/BIO_info/enhancer.txt"

with open(enhancer_file, "w") as file_enhancer:

    for item in my_list:
        i = item.nome
        start_index = item.ind_start
        end_index = item.ind_end
        diff = end_index - start_index
        for elem in fasta_list:
            if(elem.nome == i):
                seq = elem.sequence[start_index:end_index]
                file_enhancer.write(elem.nome + "\t"+ str(seq) +"\n")
                print(str(diff) +"\t"+ str(len(seq)) + "\n")